### ISSUE TITLE
binning of continuous variables 

### ISSUE THREAD

**Issue by NaasvanH** [TheProfitTable/freddiemacdata#6]
dti, cltv, fico. 
new variable for each.   
create 3 levels for each: low medium high .     
calculate: min, 33rd percentile and 66th percentile,  
bin1:  - 33rd   
bin2: 33rd - 66th
bin3: 66th +

**Comment by DandeVilliers** [comment]
Believe this is done. Just needs confirmation.

**Comment by NaasvanH** [comment]
Thanks @DandeVilliers !
