### ISSUE TITLE
Data continuity 

### ISSUE THREAD

**Issue by NaasvanH** [TheProfitTable/freddiemacdata#8]
#### Background

Background reading required for this task:

* [Freddie Mac data readme](https://github.com/TheProfitTable/freddiemacdata/blob/master/README.md)
* [Data dictionary](https://github.com/TheProfitTable/masterlibrary/blob/master/tpt_credit_datadictionary.Rmd)
* [`loanportr` package readme](https://github.com/TheProfitTable/loanportr/blob/master/README.md)
* Check out some of the function code and documentation of loanportr in [this directory](https://github.com/TheProfitTable/loanportr/tree/master/R)
* [Style guide](https://github.com/TheProfitTable/masterlibrary/blob/master/r_style_guide.Rmd)

#### Problem

The Freddie Mac data set exhibits a problem commonly found in loan data sets:  
The performance history for some contracts stops before it has to. It has to stop when there is no further information available because no more time has elapsed.   
The premature stopping of loan history typically happens because the loan has either been written off or is paid up, which results in there being no further observations (or monthly performance data) beyond a certain date or month.  

E.g., a loan is originated in May 2017. Today's date is 6 November 2017. We will have monthly performance data for this loan up to Oct 2017 (last month). The problem that I am talking about here is where, for example, the loan data only runs up to July 2017 and not October. I.e. there are no further rows. 

pointintime_month   | orig_month  | period_loan 
------------------  | -----------------  | ------------ 
2017-05             | 2017-05            | 1 
2017-06             | 2017-05            | 2
2017-07             | 2017-05            | 3

Stops here, even though it should go up to pointintime_month 2017-10. 

This is problematic because when you are trying to calculate the rate at which loans reach some status as a % of the total loans originated in the origination month, it throws out both numerator and the denominator. The loan dissapears from the total and the 'event' part of the rate calculation. Functions like`vintalyse` and `early_default` (in loanportr package)depend on monthly loan performance (rows) being populated up until the most recent `pointintime_month`. 

#### Solution 

The solution can be broken up into a few functions:  

1. Write a function that tests whether this issue is prevelant in the loan data set.   
IN: data in our [standard format](). Which, using the Freddie Mac example, is the df created in [this script](https://github.com/TheProfitTable/freddiemacdata/blob/master/data_wrangling.R)   
OUT: `TRUE` or `FALSE`

2. Write a function that gives you a list of `contract_key` numbers that exhibit this problem. 
IN: data in our [standard format](). Which, using the Freddie Mac example, is the df created in [this script](https://github.com/TheProfitTable/freddiemacdata/blob/master/data_wrangling.R)   
OUT: list of `contract_key`

3. Write a function that takes the last available row of performance information for each of the loans that are exhibiting this problem, and inserts the extra rows needed. This will be logged as a separate Issue. 

Bonus points: document your functions using a [roxygen skeleton](http://r-pkgs.had.co.nz/man.html).  You can do this by putting your cursor inside the curly bracket of the function, and in the Rstudio IDE go to Code -> Insert Roxygen Skeleton.

**Comment by DandeVilliers** [comment]
The last available month is `2017-03-31`. 

As reference here are a few loan contracts with data continuity issues: `F112Q1000550`, `F112Q1000566`, `F112Q1000590`, `F112Q1000598`

**Comment by floresfdev** [comment]
For the function (1) mentioned on the solution proposed, I think the word "prevalent" can be a bit ambiguous in this context. Should the function return `TRUE` if the percentage of trimmed contracts are greater or equal than a certain fixed value (e.g. 50%) of the total?

Instead, will it be useful (and more insightful) if the function returns the percentage of cases among the population of contracts in the dataset?

**Comment by DandeVilliers** [comment]
@floresfdev - I agree, "prevalent" might be a bit misleading. Your suggestion to return a percentage of affected cases within the population of contracts is a good idea and will be useful insight. 

I think function(1) returning a simple `TRUE`/`FALSE` is sufficient as a first barrier to quickly see if a dataset has this continuity issue. Perhaps function(2) might be a better fit to return both a list of affected contracts together with the percentage of total? That said, we are happy to bring in the percentage in either function (1) or (2). (if the output of the function is documented properly, no problem)

Appreciate the initiative.

**Comment by floresfdev** [comment]
Thanks @DandeVilliers for your feedback. I'll analyze how to proceed regarding this considerations and propose a solution.

About function (3) I know a new GH issue is mentioned to be logged, but in the meantime I'm planning to use the `padr` package ([on CRAN](https://cran.r-project.org/web/packages/padr/index.html)) to fill the missing rows for `pointintime_month` in each affected contract. Is it ok if we "guesstimate" that every other column values should be copied from the last row available (except `period_loan`)? 

Perhaps a more thorough analysis is needed, I'll reflect more about it. Any comment will be welcome.

**Comment by DandeVilliers** [comment]
@floresfdev - yes, your "guestimation" is mostly right. All column values can be copied from the last row except the following parameters:

- `loan_period` and `fpd_period`  both increment with integer value for every missing row added (numeric class)
- `pointintime_month` will increment by 1 month (last day of month) for every missing row added (Date class)

**Comment by floresfdev** [comment]
@DandeVilliers Thanks for the confirmation.
